import type { ArticleCardData } from "@/components/editorial/article-card";
import type { AuthorCardData } from "@/components/editorial/author-card";
import type { BookCardData } from "@/components/editorial/book-card";

/**
 * Dados de exemplo só para o /styleguide. Autores e obras são reais; os artigos
 * são títulos de exemplo assinados pela Redação (não atribuídos a pessoas reais).
 * Os dados definitivos chegam na Fase 2, em /content.
 */

export const sampleArticles: ArticleCardData[] = [
  {
    href: "/artigos",
    titulo: "Superexploração: o conceito que Marini deixou para o século XXI",
    linhaFina:
      "Como a teoria marxista da dependência explica a forma específica do capitalismo latino-americano.",
    autor: "Redação do Instituto",
    data: "2026-10-07",
    leituraMin: 14,
    nivel: "intermediario",
    tipo: "Ensaio",
    tema: {
      label: "Teoria marxista da dependência",
      href: "/artigos?tradicao=teoria-marxista-da-dependencia",
    },
  },
  {
    href: "/artigos",
    titulo: "Caio Prado Jr. e o sentido da colonização",
    linhaFina: "Leitura guiada do capítulo de abertura de Formação do Brasil contemporâneo (1942).",
    autor: "Redação do Instituto",
    data: "2026-09-28",
    leituraMin: 11,
    nivel: "intermediario",
    tipo: "Ensaio",
    tema: { label: "História", href: "/artigos?area=historia" },
  },
  {
    href: "/artigos",
    titulo: "Lélia Gonzalez e a categoria de amefricanidade",
    linhaFina: "Raça, classe e gênero no pensamento de uma das maiores intelectuais brasileiras.",
    autor: "Redação do Instituto",
    data: "2026-09-19",
    leituraMin: 9,
    nivel: "introdutorio",
    tipo: "Resenha",
    tema: { label: "Marxismo negro", href: "/artigos?tradicao=marxismo-negro" },
  },
  {
    href: "/artigos",
    titulo: "O que é mais-valia, em cinco minutos",
    linhaFina: "O verbete mais pedido do glossário, com exemplos do cotidiano do trabalho.",
    autor: "Redação do Instituto",
    data: "2026-09-10",
    leituraMin: 5,
    nivel: "introdutorio",
    tipo: "Verbete",
    tema: { label: "Economia política", href: "/artigos?area=economia-politica" },
  },
];

export const sampleBooks: BookCardData[] = [
  {
    slug: "o-capital-livro-1",
    href: "/biblioteca",
    titulo: "O capital: crítica da economia política, Livro I",
    tituloCapa: "O Capital, Livro I",
    autor: "Karl Marx",
    ano: 1867,
    tradicao: "marxismo-classico",
    nivel: "avancado",
    tipoDeObra: "Clássico",
    tema: { label: "Economia política", href: "/biblioteca?area=economia-politica" },
  },
  {
    slug: "sete-ensaios",
    href: "/biblioteca",
    titulo: "Sete ensaios de interpretação da realidade peruana",
    tituloCapa: "Sete ensaios",
    autor: "José Carlos Mariátegui",
    ano: 1928,
    tradicao: "socialismo-latino-americano",
    nivel: "intermediario",
    tipoDeObra: "Clássico",
    tema: { label: "Questão agrária", href: "/biblioteca?area=questao-agraria" },
  },
  {
    slug: "dialetica-da-dependencia",
    href: "/biblioteca",
    titulo: "Dialética da dependência",
    autor: "Ruy Mauro Marini",
    ano: 1973,
    tradicao: "teoria-marxista-da-dependencia",
    nivel: "intermediario",
    tipoDeObra: "Clássico",
    tema: { label: "América Latina", href: "/biblioteca?regiao=america-latina" },
  },
  {
    slug: "mulheres-raca-e-classe",
    href: "/biblioteca",
    titulo: "Mulheres, raça e classe",
    autor: "Angela Davis",
    ano: 1981,
    tradicao: "marxismo-negro",
    nivel: "introdutorio",
    tipoDeObra: "Clássico",
    tema: { label: "Feminismo marxista", href: "/biblioteca?tradicao=feminismo-marxista" },
  },
  {
    slug: "reforma-ou-revolucao",
    href: "/biblioteca",
    titulo: "Reforma ou revolução?",
    autor: "Rosa Luxemburgo",
    ano: 1899,
    tradicao: "marxismo-classico",
    nivel: "introdutorio",
    tipoDeObra: "Clássico",
    tema: { label: "Organização política", href: "/biblioteca?area=organizacao-politica" },
  },
  {
    slug: "rebelioes-da-senzala",
    href: "/biblioteca",
    titulo: "Rebeliões da senzala",
    autor: "Clóvis Moura",
    ano: 1959,
    tradicao: "marxismo-negro",
    nivel: "intermediario",
    tipoDeObra: "Clássico",
    tema: { label: "História", href: "/biblioteca?area=historia" },
  },
  {
    slug: "a-revolucao-burguesa-no-brasil",
    href: "/biblioteca",
    titulo: "A revolução burguesa no Brasil",
    autor: "Florestan Fernandes",
    ano: 1975,
    tradicao: "socialismo-latino-americano",
    nivel: "avancado",
    tipoDeObra: "Clássico",
    tema: { label: "Brasil", href: "/biblioteca?regiao=brasil" },
  },
  {
    slug: "caliba-e-a-bruxa",
    href: "/biblioteca",
    titulo: "Calibã e a bruxa",
    autor: "Silvia Federici",
    ano: 2004,
    tradicao: "feminismo-marxista",
    nivel: "intermediario",
    tipoDeObra: "Contemporâneo",
    tema: { label: "Trabalho", href: "/biblioteca?area=trabalho" },
  },
  {
    slug: "o-estado-e-a-revolucao",
    href: "/biblioteca",
    titulo: "O Estado e a revolução",
    autor: "Vladímir Lênin",
    ano: 1917,
    tradicao: "leninismo",
    nivel: "intermediario",
    tipoDeObra: "Clássico",
    tema: { label: "Teoria do Estado", href: "/biblioteca?area=teoria-do-estado" },
  },
  {
    slug: "a-conquista-do-pao",
    href: "/biblioteca",
    titulo: "A conquista do pão",
    autor: "Piotr Kropotkin",
    ano: 1892,
    tradicao: "anarquismo",
    nivel: "introdutorio",
    tipoDeObra: "Clássico",
    tema: { label: "Anarquismo", href: "/biblioteca?tradicao=anarquismo" },
  },
];

export const sampleAuthors: AuthorCardData[] = [
  {
    href: "/autores",
    nome: "José Carlos Mariátegui",
    nascimento: 1894,
    morte: 1930,
    nacionalidade: "peruano",
    tradicoes: ["Socialismo latino-americano"],
  },
  {
    href: "/autores",
    nome: "Lélia Gonzalez",
    nascimento: 1935,
    morte: 1994,
    nacionalidade: "brasileira",
    tradicoes: ["Marxismo negro", "Pensamento decolonial"],
  },
  {
    href: "/autores",
    nome: "Rosa Luxemburgo",
    nascimento: 1871,
    morte: 1919,
    nacionalidade: "polonesa e alemã",
    tradicoes: ["Marxismo clássico"],
  },
  {
    href: "/autores",
    nome: "Ruy Mauro Marini",
    nascimento: 1932,
    morte: 1997,
    nacionalidade: "brasileiro",
    tradicoes: ["Teoria marxista da dependência"],
  },
];
